# Generated by Django 3.0.7 on 2020-06-22 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=2)),
                ('postal_code', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('stars', models.FloatField()),
                ('review_count', models.FloatField()),
                ('categories', django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=10000, size=None)),
                ('review_id', models.CharField(max_length=80)),
                ('user_id', models.CharField(max_length=80)),
                ('review_stars', models.FloatField()),
                ('text', models.CharField(max_length=1000)),
                ('friends', django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=10000, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=80)),
                ('contractor', models.CharField(max_length=80)),
                ('payment', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('CL', 'Client'), ('CO', 'Contractor')], default='CL', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('business_id', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=2)),
                ('postal_code', models.IntegerField()),
                ('covid_safety', models.FloatField()),
                ('review_count', models.IntegerField()),
                ('categories', django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=80, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=2)),
                ('postal_code', models.IntegerField()),
                ('friends', django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=1000, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('is_client', 'can view the payments and friends tab'),),
            },
        ),
    ]
