# Generated by Django 3.0.7 on 2020-06-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='user_type',
            field=models.CharField(choices=[('CL', 'Client'), ('CO', 'Contractor')], default='CL', max_length=2),
        ),
    ]
