# Generated by Django 3.0.7 on 2020-06-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0004_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': (('view_payments', 'can view the payments tab'), ('view_friends', 'can view the friends tab'))},
        ),
    ]
