# Generated by Django 3.0.7 on 2020-06-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0005_auto_20200619_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': (('is_client', 'can view the payments and friends tab'),)},
        ),
    ]
