# Generated by Django 3.0.7 on 2020-06-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0006_auto_20200619_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=80)),
                ('contractor', models.CharField(max_length=80)),
                ('payment', models.IntegerField()),
            ],
        ),
    ]
