# Generated by Django 3.0.7 on 2020-06-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0007_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=80)),
                ('contractor', models.CharField(max_length=80)),
                ('payment', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
