# Generated by Django 3.0.7 on 2020-06-22 03:30

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0008_auto_20200621_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=2)),
                ('postal_code', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('stars', models.FloatField()),
                ('review_count', models.FloatField()),
                ('categories', django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=10000, size=None)),
                ('review_id', models.CharField(max_length=80)),
                ('user_id', models.CharField(max_length=80)),
                ('review_stars', models.FloatField()),
                ('text', models.CharField(max_length=1000)),
                ('friends', django_mysql.models.ListCharField(models.CharField(max_length=80), max_length=10000, size=None)),
            ],
        ),
    ]
