# Generated by Django 3.0.7 on 2020-06-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0009_rectransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractor',
            old_name='stars',
            new_name='covid_safety',
        ),
        migrations.AddField(
            model_name='client',
            name='uid',
            field=models.CharField(default=2, max_length=80),
            preserve_default=False,
        ),
    ]
